// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqliteops

import (
	"database/sql"
)

type Event struct {
	ID            string
	CreatedAt     int64
	StreamID      string
	ClientIp      sql.NullString
	TransactionID sql.NullString
	Type          string
	Level         sql.NullString
	Message       sql.NullString
	Fields        sql.NullString
}

type Stream struct {
	ID        string
	PushKey   sql.NullString
	Name      string
	CreatedAt int64
	UpdatedAt int64
}
